"""food_logs_fields

Revision ID: f2d2b60efedf
Revises: bc07eafa8785
Create Date: 2026-05-21 18:43:51.848294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f2d2b60efedf'
down_revision: Union[str, None] = 'bc07eafa8785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('food_logs', sa.Column('meal_type', sa.String(length=50), nullable=False, server_default='unknown'))
    op.add_column('food_logs', sa.Column('meal_name', sa.String(length=50), nullable=True))
    op.add_column('food_logs', sa.Column('preparation_method', sa.String(length=50), nullable=True))
    op.add_column('food_logs', sa.Column('estimated_total_calories', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('food_logs', sa.Column('fibre_g', sa.Float(), nullable=True))
    op.add_column('food_logs', sa.Column('sugar_g', sa.Float(), nullable=True))
    op.add_column('food_logs', sa.Column('sodium_g', sa.Float(), nullable=True))
    op.add_column('food_logs', sa.Column('visible_sauces_or_oils', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('food_logs', sa.Column('cuisine_type', sa.String(length=100), nullable=True))
    op.add_column('food_logs', sa.Column('restaurant_or_brand', sa.String(length=252), nullable=True))
    op.add_column('food_logs', sa.Column('ambiguity_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.execute("ALTER TABLE food_logs ALTER COLUMN image_url TYPE JSONB USING '[]'::jsonb")
    op.execute("ALTER TABLE food_logs ALTER COLUMN image_url SET NOT NULL")
    op.execute("ALTER TABLE food_logs ALTER COLUMN image_url SET DEFAULT '[]'::jsonb")
    op.drop_column('food_logs', 'origin')
    op.drop_column('food_logs', 'calories')
    op.drop_column('food_logs', 'food_name')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_logs', sa.Column('food_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('food_logs', sa.Column('calories', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('food_logs', sa.Column('origin', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('food_logs', 'image_url',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=1024),
               nullable=True)
    op.drop_column('food_logs', 'ambiguity_flags')
    op.drop_column('food_logs', 'restaurant_or_brand')
    op.drop_column('food_logs', 'cuisine_type')
    op.drop_column('food_logs', 'visible_sauces_or_oils')
    op.drop_column('food_logs', 'sodium_g')
    op.drop_column('food_logs', 'sugar_g')
    op.drop_column('food_logs', 'fibre_g')
    op.drop_column('food_logs', 'estimated_total_calories')
    op.drop_column('food_logs', 'preparation_method')
    op.drop_column('food_logs', 'meal_name')
    op.drop_column('food_logs', 'meal_type')
    # ### end Alembic commands ###
